# typed: false
# frozen_string_literal: true

# This file was generated by 'make update-formula'. DO NOT EDIT manually.
# To update: make update-formula VERSION=vX.Y.Z
class Dddns < Formula
  desc "Lightweight Dynamic DNS client with multi-provider support"
  homepage "https://github.com/descoped/dddns"
  version "0.3.1"
  license "MIT"

  if Hardware::CPU.intel?
    url "https://github.com/descoped/dddns/releases/download/v0.3.1/dddns_Darwin_x86_64.tar.gz"
    sha256 "d482163c0817ceda785689f46e9bb9d8e8b29e29c0c279e4814a98108b23b843"

    def install
      bin.install "dddns"
    end
  end

  if Hardware::CPU.arm?
    url "https://github.com/descoped/dddns/releases/download/v0.3.1/dddns_Darwin_arm64.tar.gz"
    sha256 "0c95d2759f11288b45293f71504f998d4c6a56c0ef30aacc7190f769f14fa827"

    def install
      bin.install "dddns"
    end
  end

  test do
    system "#{bin}/dddns", "--version"
  end

  def caveats
    <<~EOS
      To get started with dddns:
        1. Create configuration: dddns config init
        2. Edit configuration: vi ~/.dddns/config.yaml
        3. Test: dddns update --dry-run

      For automatic updates via cron:
        */30 * * * * /usr/local/bin/dddns update >> /var/log/dddns.log 2>&1
    EOS
  end
end