# typed: false
# frozen_string_literal: true

# This file was generated by 'make update-formula'. DO NOT EDIT manually.
# To update: make update-formula VERSION=vX.Y.Z
class Dddns < Formula
  desc "Lightweight Dynamic DNS client with multi-provider support"
  homepage "https://github.com/descoped/dddns"
  version "0.1.1"
  license "MIT"

  if Hardware::CPU.intel?
    url "https://github.com/descoped/dddns/releases/download/v0.1.1/dddns_Darwin_x86_64.tar.gz"
    sha256 "9a00919c40b319b2c1796b8f158398fa489fcf1819b9831ab56f9fcbba5139a5"

    def install
      bin.install "dddns"
    end
  end

  if Hardware::CPU.arm?
    url "https://github.com/descoped/dddns/releases/download/v0.1.1/dddns_Darwin_arm64.tar.gz"
    sha256 "2f30d1e4e453f0ae8ec363d3af7eb724d8e210928ab0151f94d57741391fccd7"

    def install
      bin.install "dddns"
    end
  end

  test do
    system "#{bin}/dddns", "--version"
  end

  def caveats
    <<~EOS
      To get started with dddns:
        1. Create configuration: dddns config init
        2. Edit configuration: vi ~/.dddns/config.yaml
        3. Test: dddns update --dry-run

      For automatic updates via cron:
        */30 * * * * /usr/local/bin/dddns update >> /var/log/dddns.log 2>&1
    EOS
  end
end