# typed: false
# frozen_string_literal: true

# This file was generated by 'make update-formula'. DO NOT EDIT manually.
# To update: make update-formula VERSION=vX.Y.Z
class Dddns < Formula
  desc "Lightweight Dynamic DNS client with multi-provider support"
  homepage "https://github.com/descoped/dddns"
  version "0.3.0"
  license "MIT"

  if Hardware::CPU.intel?
    url "https://github.com/descoped/dddns/releases/download/v0.3.0/dddns_Darwin_x86_64.tar.gz"
    sha256 "2ab27d8b147ef2a5805c1605d8473401842d098671d2130c54679029bb872859"

    def install
      bin.install "dddns"
    end
  end

  if Hardware::CPU.arm?
    url "https://github.com/descoped/dddns/releases/download/v0.3.0/dddns_Darwin_arm64.tar.gz"
    sha256 "9f8085cd05f100e8f3f385d111ac53d3b5d341229e2fb2609327cebf19914b23"

    def install
      bin.install "dddns"
    end
  end

  test do
    system "#{bin}/dddns", "--version"
  end

  def caveats
    <<~EOS
      To get started with dddns:
        1. Create configuration: dddns config init
        2. Edit configuration: vi ~/.dddns/config.yaml
        3. Test: dddns update --dry-run

      For automatic updates via cron:
        */30 * * * * /usr/local/bin/dddns update >> /var/log/dddns.log 2>&1
    EOS
  end
end